# Generated by Django 4.2.8 on 2023-12-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='is_active',
        ),
        migrations.AddField(
            model_name='material',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
