# Generated by Django 4.2.8 on 2023-12-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_material_is_active_material_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
